### ISSUE TITLE
Implement TableTestState class

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#117]
It should work like `ModelTestState` but with the table name instead of model class name

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton all works as expected for tables with `id` field, but not works for N:N tables

<img width="581" alt="image" src="https://github.com/user-attachments/assets/6004d06c-eaa0-4eb4-a27c-74d9aaf53812" />

<img width="541" alt="image" src="https://github.com/user-attachments/assets/a5e614c5-a2b3-41af-8f10-7c4ccfd36eef" />

<img width="796" alt="image" src="https://github.com/user-attachments/assets/840760b1-7143-48f3-8df1-740f2090943a" />

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/5e3a752a-fe06-47e1-8f06-e70fdb58064e" />

**Comment by DenTray** [comment]
Decided to design many-to-many tables asserting as a separate feature. This one has been released in https://github.com/RonasIT/laravel-helpers/releases/tag/3.1.2
