### ISSUE TITLE
Global export mode not affect for email testing

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#140]
Steps to reproduce:

- implement new test case with testing some email using `assertMailEquals` or update some already testable email to broke existed test
- enable global export mode using `$this->setGlobalExportMode()` helper
- run test from the first point

Actual result:
- broken test will fails

Expected result:
- content of the testable email will be exported to html fixture
- test will be completed sucessfully

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton looks good! thanks! Released in https://github.com/RonasIT/laravel-helpers/releases/tag/3.1.4
