### ISSUE TITLE
Automatically add `.json` extension

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#166]
Need to correct fixture name by adding MISSING `.json` extension for the next methods:
- `exportJson`
- `getJsonFixture`

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton perfect! thanks! Released in https://github.com/RonasIT/laravel-helpers/releases/tag/3.1.5
