### ISSUE TITLE
Implement `BaseResource` class

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#167]
Need to implement `BaseResource` class. It should extends the `Illuminate\Http\Resources\Json\JsonResource` class and contain only one public static property with name `wrap` and value - `null`

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton wors fine, thanks! Released in https://github.com/RonasIT/laravel-helpers/releases/tag/3.1.3
