### ISSUE TITLE
Error in updateMany

### ISSUE THREAD

**Issue by Goodmain** [RonasIT/laravel-helpers#33]
I got an error when call `updateMany` from the `EntityControlTrait`.

The version is 1.5.3.

```
ErrorException: Undefined variable: unUpdatedIds in /app/vendor/ronasit/laravel-helpers/src/Traits/EntityControlTrait.php:224
```

**Comment by DenTray** [comment]
Fixed in https://github.com/RonasIT/laravel-helpers/releases/tag/1.5.4
