### ISSUE TITLE
Add missing reserved filters

### ISSUE THREAD

**Issue by pirs1337** [RonasIT/laravel-helpers#44]

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
@pirs1337 `only_trashed` now not work as a filter by field `only_trashed`, but it also don't affect on the result

**Comment by pirs1337** [comment]
@DenTray, fixed, added the ability to use `only_trashed` filter in `searchQuery` method.

**Comment by DenTray** [comment]
@NikitaYakovlev @pirs1337 thanks!

**Comment by DenTray** [comment]
Released in https://github.com/RonasIT/laravel-helpers/releases/tag/2.3
