### ISSUE TITLE
Reset all repository flags after getting result

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#46]
How it works now:

```php
$userService = app(UserService::class);

$userService->onlyTrashed()->find(1);

$userService->onlyTrashed(false)->getByList([5, 10]);
```

How it should works:

```php
$userService = app(UserService::class);

$userService->onlyTrashed()->find(1);

//only trashed should be automatically reseted after repository returns results
$userService->getByList([5, 10]);
```

this logic should be implemented for all settable protected fields pf the repository class.

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
@NikitaYakovlev could you please test this one?

**Comment by NikitaYakovlev** [comment]
> @NikitaYakovlev could you please test this one?

@DenTray works as expected

**Comment by DenTray** [comment]
@NikitaYakovlev @pirs1337 thanks!

**Comment by DenTray** [comment]
Released in https://github.com/RonasIT/laravel-helpers/releases/tag/2.3
