### ISSUE TITLE
HttpRequestService call Json method on non json response

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#61]
Some APIs may return errors as a non json string

<img width="686" alt="image" src="https://user-images.githubusercontent.com/9486872/222117829-29bcb501-ee29-4124-911a-8d32ad2bee0c.png">

as a result we'll receive unclear message

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/9486872/222118306-109ab219-ff22-41eb-85b1-18be14dd6fb7.png">

I belive that the best solution here will be check if body contains a valid JSON string and throw some custom exception in this case.

**Comment by Goodmain** [comment]
@DenTray done, please check

**Comment by DenTray** [comment]
Released in https://github.com/RonasIT/laravel-helpers/releases/tag/2.3
