### ISSUE TITLE
unique_except_of_authorized_user fail with 500 if send array value

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#62]
**Steps to reproduce:**

1. apply unique_except_of_authorized_user validation rule to the string field
`'tag' => 'string|unique_except_of_authorized_user:tag`
2. try to send array value in this field

**Expected result:**

422 code error

**Actual result:**

500 code error

**Comment by DenTray** [comment]
@Goodmain as we discussed, please apply all changes for the 1 minor version as well

**Comment by Goodmain** [comment]
@DenTray Done

**Comment by DenTray** [comment]
@Goodmain changes were not merged to `major-1` branch

**Comment by Goodmain** [comment]
@DenTray done

**Comment by DenTray** [comment]
@Goodmain works great! thanks!

**Comment by DenTray** [comment]
Released in https://github.com/RonasIT/laravel-helpers/releases/tag/2.3
