### ISSUE TITLE
Update predefined filters

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#76]
As we implemented [earlier ](https://github.com/RonasIT/laravel-helpers/pull/37/files) search filters has predefine postfixes to automatically apply common filters: `_from`, `_to`, `_in_list`, `_not_in_list`.

We need to modify this list:
1. `_gt`, `_lt` postfixes should be added and works as aliases of `_from` and `_to`, but apply strict comparison
2. `_from` and `_to` postfixes should be deprecated 
3. `_gte`, `_lte` postfixes should be implemented. They should apply unstrict comparison

**Comment by Goodmain** [comment]
@DenTray All done here. Just forgot to reassign

**Comment by DenTray** [comment]
@Goodmain works as expected, thanks!

**Comment by DenTray** [comment]
Released in 2.5
