### ISSUE TITLE
Fixture trait `globalExportMode` property usage

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-helpers#89]
At the moment, trait using this property without additional checks that property exists in the class. Such behaviour disallows to use `FixtureTrait` out of the `TestCase` class.

**Comment by yogyrton** [comment]
@DenTray Done. Check it please

**Comment by KonstantinLapkovsky** [comment]
@DenTray done! Please check it

**Comment by DenTray** [comment]
@KonstantinLapkovsky works as expected, thanks!

**Comment by DenTray** [comment]
Released in https://github.com/RonasIT/laravel-helpers/releases/tag/2.4
